# Generated by Django 4.2.7 on 2023-12-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_userprofile_followers_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
