# Generated by Django 4.2.7 on 2024-01-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
