# Generated by Django 4.2.7 on 2024-01-31 14:29

import blogApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogApp', '0007_followrequest_is_accepted_followrequest_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=blogApp.models.default_profile_picture, upload_to='profile/pictures'),
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
