from django.urls import path 
from blogApp.views import (home, 
                        blog_details, 
                        profile_page, 
                        signin_page, 
                        add_comment, 
                        create_post, delete_post, update_profile,
                        search_user_profile, update_post, signout,
                        like_blog,user_profile,
                        register_user, change_password,
                        follow,unfollow,
                        accept_follow_request,
                        notification,
                        reject_follow_request)

urlpatterns = [
    path('',home, name='home-page'),
    path('blog/<int:pk>',blog_details, name='blog-page'),
    path('profile/',profile_page, name='profile-page'),
    path('login/',signin_page, name='login-page'),
    path('blog/<int:blog_id>/add_comment/', add_comment, name='add_comment'),
    path('create/', create_post, name='create_post'),
    path('blog/<int:pk>/delete/', delete_post, name='delete-post'),
    path('update/', update_profile, name='update-profile'),
    path('search/', search_user_profile, name='search-users'),
    path('blog/<int:blog_id>/update/', update_post, name='update-post'),
    path('logout/', signout, name='logout'),
    path('blog/<int:blog_id>/like', like_blog, name='like'),
    path('user/<str:username>/', user_profile, name='user_profile'),
    path('register/', register_user, name="register-page"),
    path('change_password/', change_password, name='change_password'),
    path('follow/<str:username>', follow, name='follow'),
    path('unfollow/<str:username>', unfollow, name='unfollow'),
    path('accept_follow_request/<int:follow_request_id>/', accept_follow_request, name='accept_follow_request'),
    path('notifications/', notification, name='notifications'),
    path('reject_follow_request/<int:follow_request_id>/', reject_follow_request, name='reject_follow_request'),
]
